[2024-07-22T22:23:23.786+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T22:23:23.806+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-22T22:23:22.655844+00:00 [queued]>
[2024-07-22T22:23:23.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-22T22:23:22.655844+00:00 [queued]>
[2024-07-22T22:23:23.813+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T22:23:23.824+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-07-22 22:23:22.655844+00:00
[2024-07-22T22:23:23.831+0000] {standard_task_runner.py:64} INFO - Started process 70 to run task
[2024-07-22T22:23:23.833+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-07-22T22:23:22.655844+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmps7b948q3']
[2024-07-22T22:23:23.835+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask reddit_extraction
[2024-07-22T22:23:23.874+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-22T22:23:22.655844+00:00 [running]> on host 7e89e30cc188
[2024-07-22T22:23:23.948+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ibrahim Fazili' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T22:23:22.655844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T22:23:22.655844+00:00'
[2024-07-22T22:23:23.949+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T22:23:23.961+0000] {logging_mixin.py:188} INFO - Connected to Reddit!
[2024-07-22T22:23:24.416+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T22:23:24.417+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 18, in reddit_pipeline
    load_data_to_csv(post_df_transformed, file_path)
  File "/opt/airflow/etls/reddit_etl.py", line 49, in load_data_to_csv
    post_df.to_csv(file_name, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'OUTPUT_PATH'
[2024-07-22T22:23:24.433+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-07-22T22:23:22.655844+00:00, execution_date=20240722T222322, start_date=20240722T222323, end_date=20240722T222324
[2024-07-22T22:23:24.449+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task reddit_extraction (Cannot save file into a non-existent directory: 'OUTPUT_PATH'; 70)
[2024-07-22T22:23:24.488+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-22T22:23:24.504+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T22:23:24.506+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
